<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;net6.0;netstandard2.1;net48</TargetFrameworks>
    <RootNamespace>NCoreUtils.Logging</RootNamespace>
    <!-- NuGet -->
    <PackageId>NCoreUtils.Logging</PackageId>
    <Title>$(PackageId)</Title>
    <Description>Sink based logging implementation.</Description>
    <PackageReleaseNotes></PackageReleaseNotes>
    <!-- Assembly Info -->
    <AssemblyName>$(PackageId)</AssemblyName>
    <AssemblyTitle>$(AssemblyName)</AssemblyTitle>
    <!-- Compilation -->
    <OutputType>Library</OutputType>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <!-- VERSION-SPECIFIC DEPENDENCIES -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' Or '$(TargetFramework)' == 'netstandard2.1' Or '$(TargetFramework)' == 'net6.0' ">
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
  </ItemGroup>
  <!-- POLYFILLS -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' ">
    <Compile Remove="LoggerProvider.Channels.cs" />
    <Compile Remove="Internal\ChannelReaderExtensions.cs" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' != 'netstandard2.1' And '$(TargetFramework)' != 'net6.0' And '$(TargetFramework)' != 'net10.0' ">
    <PackageReference Include="System.Threading.Channels" Version="10.0.2" />
    <Compile Remove="LoggerProvider.BlockingCollection.cs" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
    <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
    <Compile Remove="LoggerProvider.BlockingCollection.cs" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
    <Compile Remove="LoggerProvider.BlockingCollection.cs" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Compile Include="..\Shared\Nullable\*.cs" />
  </ItemGroup>
  <!-- COMMON DEPENDENCIES -->
  <ItemGroup>
    <ProjectReference Include="..\NCoreUtils.Logging.Abstractions\NCoreUtils.Logging.Abstractions.csproj" />
  </ItemGroup>
</Project>
