<Project>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>10.0.0-rc01</Version>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>Artyom Antyipin</Authors>
    <Copyright>Artyom Antyipin</Copyright>
    <RepositoryUrl>https://github.com/artyomszasa/NCoreUtils.Logging.git</RepositoryUrl>
    <Product>NCoreUtils</Product>
    <!-- <GenerateDocumentationFile>true</GenerateDocumentationFile> -->
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
</Project>
